## Imports

In [46]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

## Data Ingestion

In [19]:
# AP Poll Data - This dataset contains the scores of previous tournament games. Every two rows is a game.

poll_data = pd.read_csv("data/AP Poll Data.csv")

In [20]:
# Ingestion Check
poll_data.head()

,YEAR,WEEK,TEAM NO,TEAM,SEED,ROUND,W,L,AP VOTES,AP RANK,RANK?
0,2026,1,1173.0,Purdue,2.0,0.0,0.0,0.0,1485.0,1.0,1
1,2026,1,1199.0,Houston,2.0,0.0,0.0,0.0,1459.0,2.0,1
2,2026,1,1206.0,Florida,1.0,0.0,0.0,0.0,1382.0,3.0,1
3,2026,1,1208.0,Connecticut,2.0,0.0,0.0,0.0,1299.0,4.0,1
4,2026,1,1165.0,St. John's,5.0,0.0,0.0,0.0,1203.0,5.0,1

In [21]:
# Barttovrik Away-Neutral - This dataset contains the Barttorvik team data for away and neutral games. Team's away and neutral games only count towards this data.

bartt_awaynetural = pd.read_csv("data/Barttorvik Away-Neutral.csv")

In [22]:
# Ingestion Check
bartt_awaynetural.head()

,YEAR,TEAM NO,TEAM ID,TEAM,SEED,ROUND,BADJ EM,BADJ O,BADJ D,BARTHAG,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
0,2026,1215,2,Akron,12,0,12.8,116.2,103.4,0.793,...,77,362,363,38,164,220,207,14,51,262
1,2026,1214,3,Alabama,4,0,25.4,127.5,102.1,0.928,...,3,89,76,294,8,28,67,8,209,21
2,2026,1213,8,Arizona,1,0,34.9,127.8,92.9,0.975,...,71,8,26,324,9,188,192,15,31,7
3,2026,1212,10,Arkansas,4,0,23.6,125.5,101.9,0.917,...,30,30,49,309,6,230,298,22,276,4
4,2026,1211,25,BYU,6,0,21.3,123.1,101.8,0.899,...,45,70,98,307,48,103,41,39,113,51

In [23]:
# Coach Results - This dataset contains the tournament results for head coaches since 2008. 
coach_results = pd.read_csv("data/Coach Results.csv")

In [24]:
# Ingestion Check
coach_results.head()

,COACH ID,COACH,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,F4%,CHAMP%
0,1,Tom Izzo,8.8,1,10.3,1,51,35,16,0.686,16,14,10,6,4,1,0,5,88.60%,35.50%
1,2,John Calipari,7.6,3,9.8,2,55,41,14,0.745,15,13,11,8,5,3,1,8,99.00%,75.00%
2,3,Brad Stevens,6.5,4,7.6,3,17,12,5,0.706,5,4,2,2,2,2,0,0,25.50%,3.70%
3,4,Dana Altman,6.0,5,6.5,4,26,17,9,0.654,9,9,5,2,1,0,0,1,44.20%,8.30%
4,5,John Beilein,5.5,7,6.5,5,28,19,9,0.679,9,7,5,3,2,2,0,2,65.90%,21.50%

In [25]:
# Conference Results - This dataset contains the tournament results for conferences since 2008. 
conference_results = pd.read_csv("data/Conference Results.csv")

In [26]:
# Ingestion Check
conference_results.head()

,CONF ID,CONF,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,CHAMP%
0,2,ACC,15.2,1,10.2,1,255,161,94,0.631,99,66,44,26,13,7,5,28,96.40%
1,14,Horz,5.9,4,7.9,2,31,13,18,0.419,18,5,2,2,2,2,0,0,3.70%
2,28,SEC,6.6,2,7.5,3,228,134,94,0.588,96,59,37,23,10,3,2,18,92.30%
3,24,P12,6.1,3,7.3,4,146,83,63,0.568,63,44,27,9,3,0,0,9,66.50%
4,6,B10,2.2,8,5.9,5,271,159,112,0.587,112,84,43,17,10,5,0,21,93.00%

In [27]:
# Conference Stats Away Neutral - This dataset contains the Barttorvik Conference data for away and neutral games. Conference teams' away and neutral games only count towards this data. All of the statistics below are an average of all teams in a conference, except for G, W, and L as those are cumulative statistics. 
conference_stats = pd.read_csv("data/Conference Stats Away Neutral.csv")

In [28]:
# Ingestion Check
conference_stats.head()

,YEAR,CONF ID,CONF,BADJ EM,BADJ O,BADJ D,BARTHAG,G,W,L,...,AVG HGT,EFF HGT,EXP,TALENT,FT%,OP FT%,PPPO,PPPD,ELITE SOS,WAB
0,2026,1,A10,4.2,109.9,105.7,0.610,222,94,128,...,77.320,80.480,2.050,17.554,71.4,71.7,1.055,1.095,26.390,-3.50
1,2026,2,ACC,16.6,118.2,101.6,0.851,271,122,149,...,78.069,81.107,1.798,55.261,71.3,73.7,1.094,1.111,47.966,0.29
2,2026,3,AE,-15.6,99.5,115.1,0.158,162,42,120,...,76.993,80.087,1.703,6.229,69.6,71.6,0.991,1.128,13.937,-10.00
3,2026,4,Amer,2.0,109.4,107.4,0.553,210,94,116,...,77.342,80.448,1.951,24.405,72.4,72.4,1.059,1.106,23.642,-3.90
4,2026,5,ASun,-10.1,104.9,115.0,0.258,219,63,156,...,77.215,80.117,1.743,7.524,71.8,73.0,1.055,1.176,18.774,-8.70

In [29]:
# Heat Check Ratings - Heat Check CBB’s Ratings are a set of advanced team ratings used to evaluate and project how teams might perform in the NCAA Tournament. 
heat_check_ratings = pd.read_csv("data/Heat Check Ratings.csv")

In [30]:
# Ingestion Check
heat_check_ratings.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,EASY DRAW,TOUGH DRAW,DARK HORSE,UPSET ALERT,CINDERELLA
0,2026,1188,Louisville,6,0,False,False,True,False,False
1,2026,1163,Tennessee,6,0,False,False,True,False,False
2,2025,1135,Connecticut,8,32,False,False,True,False,False
3,2025,1103,Oklahoma,9,64,False,True,False,False,False
4,2025,1115,Memphis,5,64,False,True,False,True,False

In [31]:
# Heat Check Tournament Index - Heat Check CBB’s Tournament Index are a set of advanced team ratings used to evaluate and project how teams might perform in the NCAA Tournament. 
heat_check_index = pd.read_csv("data/Heat Check Tournament Index.csv")

In [32]:
# Ingestion Check
heat_check_index.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,POWER,PATH,DRAW,WINS,POOL VALUE,POOL S-RANK,NCAA S-RANK,VAL Z-SCORE,POWER-PATH
0,2026,1215,Akron,12,0,63.2,83.4,NaN,NaN,2.4,47,48,NaN,-20.2
1,2026,1214,Alabama,4,0,84.4,72.4,NaN,NaN,32.3,13,14,NaN,12.0
2,2026,1213,Arizona,1,0,94.0,66.1,NaN,NaN,84.6,2,2,NaN,27.9
3,2026,1212,Arkansas,4,0,82.5,67.8,NaN,NaN,45.9,10,16,NaN,14.7
4,2026,1211,BYU,6,0,78.3,72.9,NaN,NaN,16.7,23,24,NaN,5.4

In [33]:
# Resumes - This dataset contains the resume data for tournament teams. 
resumes = pd.read_csv("data/Resumes.csv")

In [34]:
# Ingestion Check
resumes.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,NET RPI,RESUME,WAB RANK,ELO,B POWER,Q1 W,Q2 W,Q1 PLUS Q2 W,Q3 Q4 L,PLUS 500,R SCORE,BID TYPE
0,2026,1215,Akron,12,0,53,114,53,27,70.7,0,0,0,1,23,0.91,Auto
1,2026,1214,Alabama,4,0,18,14,14,23,16.7,7,9,16,0,15,99.45,At-Large
2,2026,1213,Arizona,1,0,3,3,3,2,3.0,16,8,24,0,31,99.98,Auto
3,2026,1212,Arkansas,4,0,16,17,15,11,19.0,8,8,16,0,19,99.51,Auto
4,2026,1211,BYU,6,0,22,21,22,38,24.7,7,8,15,0,12,98.40,At-Large

In [36]:
# Seed Results - This dataset contains the tournament results for seeds since 2008. 
seed_results = pd.read_csv("data/Seed Results.csv")

In [37]:
# Ingestion Check
seed_results.head()

,SEED,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,CHAMP%
0,11,14.2,2,14.8,1,127,59,68,0.465,68,33,16,6,4,0,0,0,11.80%
1,15,3.8,5,5.2,2,80,12,68,0.150,68,7,4,1,0,0,0,0,0.00%
2,3,5.9,3,4.0,3,196,129,67,0.658,68,60,40,20,5,3,1,0,80.70%
3,4,2.5,6,3.8,4,177,110,67,0.621,68,53,37,11,6,2,1,0,75.80%
4,8,-0.3,8,3.0,5,119,51,68,0.429,68,35,7,3,3,3,0,0,16.30%

In [38]:
# Shooting Splits - This dataset contains the shooting split data for the tournament teams. 
shooting_splits = pd.read_csv("data/Shooting Splits.csv")

In [40]:
# Ingestion Check
shooting_splits.head()

,YEAR,TEAM NO,TEAM ID,TEAM,CONF,DUNKS FG%,DUNKS SHARE,DUNKS FG%D,DUNKS D SHARE,CLOSE TWOS FG%,...,CLOSE TWOS FG%D RANK,CLOSE TWOS D SHARE RANK,FARTHER TWOS FG% RANK,FARTHER TWOS SHARE RANK,FARTHER TWOS FG%D RANK,FARTHER TWOS D SHARE RANK,THREES FG% RANK,THREES SHARE RANK,THREES FG%D RANK,THREES D SHARE RANK
0,2026,1215,2,Akron,MAC,93.1,7.9,87.0,4.2,65.0,...,67,159,22,57,50,295,14,65,256,305
1,2026,1214,3,Alabama,SEC,85.9,10.1,92.7,7.6,61.4,...,86,152,17,14,145,34,72,1,160,52
2,2026,1213,8,Arizona,B12,93.4,9.0,91.4,6.1,64.1,...,19,8,31,345,86,2,62,363,46,109
3,2026,1212,10,Arkansas,SEC,92.0,15.4,87.1,9.8,67.1,...,291,224,307,227,177,174,8,311,56,144
4,2026,1211,25,BYU,B12,84.2,10.4,81.2,8.0,66.9,...,296,14,44,292,153,8,130,174,266,177

In [42]:
# Team Results - This dataset contains the tournament results for teams since 2008. 
team_results = pd.read_csv("data/Team Results.csv")

In [43]:
# Ingestion Check
team_results.head()

,TEAM ID,TEAM,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,F4%,CHAMP%
0,1,Abilene Christian,0.7,53,0.7,55,3,1,2,0.333,2,1,0,0,0,0,0,0,0.10%,0.00%
1,2,Akron,-1.2,201,-1.5,208,6,0,6,0.000,6,0,0,0,0,0,0,0,0.50%,0.00%
2,3,Alabama,0.8,47,0.2,78,19,12,7,0.632,7,5,4,2,1,0,0,3,62.40%,19.80%
3,4,Alabama St.,0.0,92,0.0,94,1,0,1,0.000,1,0,0,0,0,0,0,0,0.00%,0.00%
4,4,Albany,-0.4,163,-0.3,162,3,0,3,0.000,3,0,0,0,0,0,0,0,0.00%,0.00%

In [44]:
# Tournament Matchups - This dataset contains the scores of previous tournament games. Every two rows is a game. For example, the first row in the 2025 YEAR has Auburn, and the second row has Alabama St. Those two teams played against each other in the First Round, and Auburn won the game 83 - 63. The following game was Louisville vs Creighton, where Creighton won the game 89 - 75. 
tournament_matchups = pd.read_csv("data/Tournament Matchups.csv")

In [45]:
# Ingestion Check
tournament_matchups.head()

   YEAR  BY YEAR NO  TEAM NO        TEAM  SEED  ROUND  CURRENT ROUND  SCORE
0  2026        2288     1207        Duke     1      1             64    NaN
1  2026        2287     1168       Siena    16     64             64    NaN
2  2026        2286     1176    Ohio St.     8      1             64    NaN
3  2026        2285     1164         TCU     9     64             64    NaN
4  2026        2284     1165  St. John's     5      1             64    NaN

In [48]:
# Scraping

url = 'https://en.wikipedia.org/wiki/List_of_NCAA_Division_I_men%27s_basketball_tournament_venues'
response = requests.get(url)

print(response)
print(response.text)

<Response [403]>
Please set a user-agent and respect our robot policy https://w.wiki/4wJS. See also https://phabricator.wikimedia.org/T400119.